name = "mcp-oauth-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV namespace - single namespace for all OAuth data
[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"  # Replace with your actual KV namespace ID

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "KV"
id = "YOUR_PRODUCTION_KV_ID"  # Replace with production KV namespace ID

[[env.production.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# Routes are managed via API to avoid conflicts
# [[env.production.routes]]
# pattern = "your-subdomain.your-domain.com/*"
# zone_id = "YOUR_ZONE_ID"

[observability]
enabled = true

# Cron trigger for periodic cleanup (runs every hour)
[triggers]
crons = ["0 * * * *"]

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]